### PR TITLE
feat(nav): Add mobile styles for navigation

### LINKED ISSUE #106: Navigation is cut off for smaller screens
**Problem Description:**
All the navigation links at the top are not visible on smaller screens.
screen shot 2017-06-12 at 23 56 00

**Suggested Solution:**
Maybe wrap the elements.

### PR DESCRIPTION
**Pull request by paulmolluzzo**
#26, closes #106

**What**: Adds mobile styles for navigation to match designs in #26 

**Why**: Fixes #106 

**How**: New toggle was added and media queries used to display selectively.

screen shot 2017-06-12 at 10 36 23 pm
screen shot 2017-06-12 at 10 36 35 pm

### CODE REVIEW

**Comment by kentcdodds** [comment]
Sorry about that @paulmolluzzo, I merged the a11y PR and I guess this conflicted :-/

**Comment by paulmolluzzo** [comment]
No worries @kentcdodds. I won't have a chance to look at this until tomorrow, but can resolve the conflict next chance I get.

**Comment by paulmolluzzo** [comment]
@kentcdodds Fixed the conflict and an issue with active links.

**Comment by kentcdodds** [comment]
Super!

**Pull request merged**
