### PR TITLE
docs($browser): add get-started part of doc(basics) 

### PR DESCRIPTION
**Pull request by liadbiz**
#82 

**What**:  move get-started part of README file in glamorous repo to glamorous website

**Why**: Updating glamorous-website with existing glamorous documentation.

**How**: copy content in README file of glamorous repo to `/pages/basics/content/getting-started.js`
and add a basic example that with react-live.

exmaple

but the content it render is on the top.....

### CODE REVIEW

**Comment by kentcdodds** [comment]
This is great! Thank you so much! I'll give it a look tomorrow (I try to limit my OSS stuff on Sundays).

**Comment by liadbiz** [comment]
@kentcdodds As you can see, all commits of another PR I made are listed here, I have no idea how to solve this :cry:

**Comment by kentcdodds** [comment]
You need to make sure you're using different branches for each of your pull requests. If you haven't already, you may consider watching [this free course](https://kcd.im/pull-request) on how to contribute to OSS as it demos a pretty good workflow.

**Comment by liadbiz** [comment]
@kentcdodds  nice course! Thank you so much! Can I close this pr and create a new one?

**Pull request closed without merging**
