### PR TITLE
Improve homepage and add react-live

### LINKED ISSUE #12: Use React Live?
I'm pretty sure this is what Styled-Components uses for their site: https://react-live-demo.philpl.com/

### PR DESCRIPTION
**Pull request by paulmolluzzo**
**What**: Adds a live example to the homepage using `react-live`

**Why**: Fixes #12 and continues the work on #8

**How**: I wrote code. 😜

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
@kentcdodds Any thoughts on the tests and/or code coverage?

**Comment by kentcdodds** [comment]
Cool! On mobile right now, but that preview thing is slick!

Also, we should probably do something about mobile 😅

**Comment by kentcdodds** [comment]
screenshot_20170530-214424
screenshot_20170530-214427

**Comment by paulmolluzzo** [comment]
We can stack the editor and view I guess.

Mobile needs a bit of attention, yeah. 🤕

**Comment by bulby97** [comment]
Cool !

IMO I find the way styled-components is doing is better. 
The two buttons at the top of the LivePreview are directly linked to it.

That way you have that minimalist design and behavior, and it feels awesome to impact directly on the website.

**Comment by paulmolluzzo** [comment]
I like @bulby97's thought, does that work for everyone? What about the code examples we do on guides? Do we plan to do a similar arrangement where the result is "part of the website" and less like an embedded view?

**Comment by paulmolluzzo** [comment]
Alright, I pushed an update that has the buttons editable with the code example and it is SWEET! 🍬

**Comment by kentcdodds** [comment]
I'm in love with `stage-ci` 😍 https://glamorous-website-pr-improve-homepage.now.sh/

**Comment by bulby97** [comment]
This is sweeeettt, but waaayyyyyyyyy too long 😬

**Comment by kentcdodds** [comment]
Was going to leave some comments, but I think I'll just make the modifications myself and we can talk about them :)

**Comment by kentcdodds** [comment]
Took way longer than expected because I was wrestling with some testing issues. Got those resolved though. Also I did more than I intended 😅

**Comment by kentcdodds** [comment]
Let's go ahead and merge this as-is. We can keep working on stuff going forward :)

**Pull request merged**
