### PR TITLE
remove rc!

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: Remove the rc

**Why**: Because we're getting ready to release this and I want the website ready before we announce it.

**How**: Remove the `rc.` from the `now-travis` file

### CODE REVIEW

**Comment by tdeschryver** [comment]
Seems like every `process.env` which is being used is broken at run time? :thinking: 
- `process.env.LOCALE`: current language in `locale-chooser`
- `process.env.LOCALE`: Twitter card prefix
- `process.env.LOCALE`: `components\utils\locale`
- `process.env.USE_PREFETCH`: in nav anchor tags

**Comment by kentcdodds** [comment]
Yeah, I just noticed that as well... It's weird because I added the babel plugin which should transpile that... Could you try to give that a look? If we have to I'm happy to add the webpack define plugin back in...

**Comment by tdeschryver** [comment]
Think the solution would be to use `[babel-plugin-transform-inline-environment-variables](https://babeljs.io/docs/plugins/transform-inline-environment-variables/)` instead of `babel-plugin-transform-node-env-inline`. Let me run some more tests to be completely sure.

**Comment by kentcdodds** [comment]
Sounds great! Could you put up a PR for that?

**Comment by tdeschryver** [comment]
Of course! :smile:

**Pull request merged**
