### PR TITLE
Update prop styles example

### PR DESCRIPTION
**Pull request by peterschussheim**
**What**:

- [x] update codesandbox example and add link to `prop-styles`
- [x] bump `babel-macros` and `nps version`: Referencing #283, I had this issue too and fixed it with version updates.  I am not sure if this fixes the problem for all users.
- [x] update .gitignore and commit package-lock

**Why**:

- I'd like to expose more `glamorous` users to the `prop-styles` utility

**How**:

[View deployed build](https://en-glamorous-xspzqgxrxi.now.sh).

### CODE REVIEW

**Comment by peterschussheim** [comment]
Failing on Travis due to:

```
The macro imported from "preval.macro" must be wrapped in "createMacro" which you can get from "babel-macros".
```

Could this be due to the version bump?  All local tests pass:
iterm2001

**Comment by kentcdodds** [comment]
Yeah, there's an old version of something. I've cleared the travis cache. We'll see what happens with the new build.

**Comment by kentcdodds** [comment]
Oh, I just realized what's going on. You used `npm` to install dependencies. But this repo uses `yarn`. If you could remove the `package-lock.json` file and then use `yarn` to install dependencies that would fix it (it'll update the `yarn.lock` file). Also, you'll need to pull my changes before you do any of this. Thanks!

P.S. I really don't like committing lockfiles in open source projects... But that's what we're doing in this one so we'll just have to do that.

**Comment by peterschussheim** [comment]
awesome! 👍

**Pull request merged**
