### PR TITLE
update contributors list. Thanks everyone!!!

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: Updates the `.all-contributorsrc` file to include everyone who's contributed to this project!

**Why**: Because we're really grateful for everyone's contributions (even non-code contributions)

**How**: using the `all-contributors-cli` mostly.

cc @paulmolluzzo, @liadbiz, @bulby97, @parvezk, @williamolojede, @mjaltamirano, @whoisandy, @TreTuna, @irth, @aranajhonny, @anthony2025, @tdeschryver, @mwickett, @danseethaler, @yuanchuan, @philpl, @HsinChiehYeh, @bernard-lin, @Macxim, @etiennetalbot, @karlgroves, @Belelros, @lydell, @Anujan, @CarlRosell, @aarondolson, @gillchristian, @jonmajorc, @hozefaj, @audoralc, @Hossman333, @vesparny, @avivr, @ajwhite

Thank you all so much. If you'd prefer to not appear in this list, please let me know and I'll remove you. We can wait a few hours before merging.

Thanks again! :tada:

### CODE REVIEW

**Comment by kentcdodds** [comment]
By the way, here's what the README looks like with these changes: https://github.com/kentcdodds/glamorous-website/blob/76ca94626ea8827490e7b15eb2d9a169d70aec3c/README.md#contributors

**Comment by bernard-lin** [comment]
Woo! Thanks, Kent! 😄

**Comment by kentcdodds** [comment]
Just added @nitin42 as well :smile:

**Comment by paulmolluzzo** [comment]
@kentcdodds can you center the icon in the README like you did for `glamorous`? Thanks!

**Comment by kentcdodds** [comment]
Done!

**Comment by paulmolluzzo** [comment]
Awesome! Thank you to everyone who contributed! 🙌 I am so stoked to see this site launch! 🎉

**Pull request merged**
