### PR TITLE
docs($browser): add glamorous component factory info to docs

### PR DESCRIPTION
**Pull request by williamolojede**
#79
**What**: transferred the glamorousComponentFactory section from the glamorous github README to the
glamorous website

### CODE REVIEW

**Comment by kentcdodds** [comment]
This is great! Thank you so much! I'll give it a look tomorrow (I try to limit my OSS stuff on Sundays).

**Comment by williamolojede** [comment]
okay, looking forward to that

**Comment by kentcdodds** [comment]
By the way, would you like to [add yourself](https://github.com/kentcdodds/glamorous-website/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to [the contributors table](https://github.com/kentcdodds/glamorous-website/blob/master/README.md#contributors)? If you want to do it, then open a new pull request :) Thanks again!

**Comment by williamolojede** [comment]
feels good to have my first pr merged, will take on others now and also add myself to the contributors table. thanks for the opportunity

**Pull request merged**
