### PR TITLE
docs(french): translation in french (last part)

### PR DESCRIPTION
**Pull request by forresst**
**What**: Translation in french (second part)

**Why**: Documentation in several languages is better

**How**: Several tranlations:

* Integrations
* Updates from the original

### CODE REVIEW

**Comment by forresst** [comment]
cc @Macxim and @etiennetalbot 😄

**Comment by Macxim** [comment]
LGTM too 👍

**Comment by forresst** [comment]
I declare that the French translation is 100% up to date ✌️ 

Thank you to all those who helped me in this task.

**Comment by paulmolluzzo** [comment]
Wow, thank you @forresst @Macxim and @bulby97! (And everyone else who helped with this!)

**Comment by kentcdodds** [comment]
Wahoo! Thank you so much. We all really appreciate it. Would be great if you could watch the repo for changes to content to keep things updated. Feel free to recruit others to help as well!

**Pull request merged**
