### PR TITLE
Port to next

### PR DESCRIPTION
**Pull request by paulmolluzzo**
This is a super rough port of the [CodeSandbox](https://codesandbox.io/s/59XX9B1MR) example to [`next`](https://github.com/zeit/next.js).

A bunch of stuff is missing:

* No internationalization
* No actual documentation
* No style work done at all (whatever @kentcdodds did is here)
* External links are busted at the moment (but I'll probably push in a few minutes

You can see what this is like here: https://glamorous-website-ppjkgdtyuu.now.sh

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
Fixed the external links issue.

**Comment by kentcdodds** [comment]
Awesome. Thank you :)

**Comment by paulmolluzzo** [comment]
I should've updated the README. :man_facepalming:

**Comment by hozefaj** [comment]
@paulmolluzzo How do I run this locally to see how it looks?

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo How do I run this locally to see how it looks?

LOL, yeah, I didn't write a README.

`npm install` then `npm run dev`.

See also https://github.com/kentcdodds/glamorous-website/pull/3

**Comment by paulmolluzzo** [comment]
@hozefaj sorry about that.

**Pull request merged**
