### PR TITLE
Add in basic README

### PR DESCRIPTION
**Pull request by paulmolluzzo**
Super basic. If there's anything else you want in here please let me know. Code of Conduct, License, etc.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Yeah, let's MIT license it and add the contributor convenient 👍

**Comment by kentcdodds** [comment]
I'll give you push rights when I get back to a keyboard

**Comment by paulmolluzzo** [comment]
Cool. Or you can merge this and do whatever magic you do to make sure there's a clean way to add contributors, write commit messages, etc. I'm also listed as the author in the `package.json`, and you can change that if you want. It's MIT in the `package.json` at least.

**Comment by kentcdodds** [comment]
I really dislike the author stuff in the `package.json`. Despite this, I think that we should just leave the author field to the one who created the `package.json` :) So we'll stick with you there.

As for the license, we can leave that to you too, and maybe add PayPal later I guess 🙃

All this stuff just gets in the way of us writing cool stuff. How annoying.

**Comment by paulmolluzzo** [comment]
Yeah, I hear ya. Whatever makes this easiest to get people writing code so we can get this live. Hopefully there's enough in the README for folks to get rolling for now at least.

**Pull request merged**
