### PR TITLE
Global list styling

### PR DESCRIPTION
**Pull request by tdeschryver**
**What**: Added global list styling 
**Why**: Remove the weird looking lists as discussed in #163 
**How**: Added styling in `styles/base.js`

**Places that have lists:**
- Basics - Installation
- Advanced - Optimizing Bundle Size
- Advanced - Improved Experience
- Api - Complete support - config
- Api - CSS property safety
- Api - No Support

**Side note**:
The checkbox still looks strange (Api - Complete support - config), but I think the checkbox can be replaced with [https://github.com/paypal/glamorous#usedisplaynameinclassname](https://github.com/paypal/glamorous#usedisplaynameinclassname)?

How it looks now:
image

How it is going to look:
image

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
This could use some `padding` on the top and bottom of `li`s as well. And if we're going to keep the actual bullets maybe we want to use something besides the default? Something prettier?

**Comment by tdeschryver** [comment]
@paulmolluzzo any suggestions for the bullets? Something default like squares, a custom image, or ...?

**Comment by tdeschryver** [comment]
and what do you think about some padding left?

image

**Comment by paulmolluzzo** [comment]
I have a silly, kind of cute idea:

```css
ul { list-style-type: "💋"; }
```

Kind of goes with the idea of the `glamorous` logo.

I agree about needing padding. It just looks like we've reset a lot of the `padding`/`margin`/`line-height` and didn't reintroduce anything to make it easy to read. Speaking of which, I wouldn't mind of @mwickett took a look at this PR to ensure we make this easy to read. I don't think `padding`/`margin`/`line-height` is a a11y issue _per se_, but he might have some thoughts regardless.

**Comment by mwickett** [comment]
Definitely agree that lists need to be indented with some padding-left. Also, list items could use some margin-bottom. The screenshot below has `padding-left: 1.5em` and `li { margin-bottom: 10px }`

screenshot 2017-06-21 09 48 03

Now, after messing with it a bit, I actually think it'd be worth doing a type overhaul – things are pretty crowded, and the font-weight is a bit too heavy. Block level text elements (`p, code, ul, ol, h1, h2, h3, h4, h5, h6`) need some vertical space. I should have time in the next couple days to take put together a PR, or someone else ( @tdeschryver ?) can take a crack.

@paulmolluzzo The idea of the emoji as a bullet may work - would be good to see it in action as a test. It would add some "brand", but they also may be too small to be "legible" Worth a shot!

**Comment by tdeschryver** [comment]
@mwickett Seems like you're the best person suited for the job, so you can just go ahead and take this one  . Should I close this PR or ...?

**Comment by kentcdodds** [comment]
Thanks for working on this! I love the idea of the 💋 for bullets. However I can't help but wonder whether some folks would find it unnecessarily distracting (particularly those with ADHD or other challenges).

**Comment by paulmolluzzo** [comment]
> However I can't help but wonder whether some folks would find it unnecessarily distracting (particularly those with ADHD or other challenges).

We have a bright pink website with expanding/collapsing sections and live editing of site components. With all that interactivity I don't think the list icon is going to be the thing that distracts people.

And not to be insensitive, but for most people this will be a nice design touch. For an unknown (small?) number people this _might_ be a small distraction in a website that's already pretty distracting. 😉

**Comment by kentcdodds** [comment]
Yep, I'm good with that. Let me know when this is ready for another review :)

**Comment by tdeschryver** [comment]
Would look like;

capture

**Comment by kentcdodds** [comment]
I'm willing to give it a try!

**Comment by kentcdodds** [comment]
If you look at the diff on this PR it shows nothing's changed. 🤔 

I would recommend that instead of merging `master` into your branches you rebase your branches onto master. [This might be helpful](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch) :)

**Comment by paulmolluzzo** [comment]
It's hard for me to tell, are the bullet kisses black? They should be red/pink. `li` bullets take the `color` of the `li` AFAIK, so we'll probably have to use a pseudo-element like `:before` to make it look like I have in mind. Something like:

```js
'&::before': {
  content: `'💋'`,
  color: colors.primaryMed
}
```

**Comment by tdeschryver** [comment]
@paulmolluzzo color in screen is indeed blackish.

Now with color:
image

`css` looks like (in `base.js`):
```
li:before {
  content: "💋";
  margin-right: 5px;
  color: ${colors.primaryMed};
}
```

**Comment by paulmolluzzo** [comment]
Nice! It's a cute touch I think.

**Comment by tdeschryver** [comment]
I agree, I'll walk through the pages and if its OK ill push my changes :smile:

**Comment by paulmolluzzo** [comment]
@tdeschryver I think the commit where `master` was merged in undid some changes you had done for this PR. 😕 @kentcdodds had commented someplace with a link to rebasing PRs, so maybe that'll help?

**Comment by tdeschryver** [comment]
@paulmolluzzo My bad I accidentally merged, but  [this](https://github.com/kentcdodds/glamorous-website/pull/168/commits/3805411d9b910f88370b02b3ff888369376eaac5) was my only commit. 
The changes in #170  are overruling my changes, so I basically wanted to discharge my changes.

**Comment by paulmolluzzo** [comment]
@tdeschryver I'm on mobile, so really as long as it looks OK when rendered then sure. 🤷🏻‍♂️

**Pull request merged**
