### PR TITLE
Docs(french): Change getting started

### PR DESCRIPTION
**Pull request by forresst**
**What**: Translation in french "Copy get-started part in readme into website" (Related #164)

**Why**: Documentation in several languages is better

**How**: Translate in french

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
cc @Macxim @bulby97 @etiennetalbot 🇫🇷 

@kentcdodds Perhaps we'd like some of these people to be collaborators so we can assign reviews to them? If they are willing to contribute of course. 😄

**Comment by paulmolluzzo** [comment]
@kentcdodds oh, and can we add labels for each of the languages please? Will make it easier to find relevant issues/PRs if people want to focus on a particular language of the site.

**Comment by forresst** [comment]
I am a volunteer for the reviews of translations in French (except of course my own translations)

**Comment by kentcdodds** [comment]
Again, things have changed a little bit. We're no longer using js files, we're using markdown. Please see the [updated docs](https://github.com/kentcdodds/glamorous-website/blob/master/other/CONTRIBUTING_DOCUMENTATION.md) :)

This should be much better! :tada:

**Pull request closed without merging**
