### PR TITLE
Made Nav component localisable

### LINKED ISSUE #134: Make nav localizable.
Right now it's only in English. I think it should be pretty straightforward with the `withContent` HoC.

### PR DESCRIPTION
**Pull request by irth**
Closes #134

**What**:
I changed the Navbar to use withContent HoC so that it can be translated

**Why**:
To ensure that the entire website can be accessible in other languages

**How**:
* I removed the default export from the Nav class and replaced it with withContent export.
* I moved the text over to content/nav.js and replaced it with {this.props.content.*}.

### CODE REVIEW

**Comment by forresst** [comment]
Awesome !

Here is the contents of the file for the French version (`/glamorous-website/components/content/fr/nav.js`) :
```js
module.exports = {
  home: 'Accueil',
  basics: 'Bases',
  advanced: 'Avancés',
  examples: 'Exemples',
  integrations: 'Intégrations',
  api: 'API',
}
```
Can you add it? Or I would do it after the merge in the master.

**Comment by irth** [comment]
@forresst Sure! Thanks.

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

**Comment by irth** [comment]
I tried to do that just now but the precommit hook seems to fail :/
```
$ cat /home/me/.npm/_logs/2017-06-15T16_45_28_940Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/me/.nvm/versions/node/v7.10.0/bin/node',
1 verbose cli   '/home/me/.nvm/versions/node/v7.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'precommit' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'precommit' ]
5 info lifecycle glamorous-website@1.0.0~precommit: glamorous-website@1.0.0
6 verbose lifecycle glamorous-website@1.0.0~precommit: unsafe-perm in lifecycle true
7 verbose lifecycle glamorous-website@1.0.0~precommit: PATH: /home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/home/me/dev/contrib/glamorous-website/node_modules/.bin:/home/me/opt/miniconda3/bin:/home/me/.rbenv/shims:/home/me/.rbenv/bin:/home/me/.nvm/versions/node/v7.10.0/bin:/home/me/.pyenv/plugins/pyenv-virtualenv/shims:/home/me/.pyenv/shims:/home/me/.pyenv/bin:/home/me/opt/miniconda3/bin:/home/me/opt/flutter/bin:/home/me/bin:/home/me/.pyenv/plugins/pyenv-virtualenv/shims:/home/me/.pyenv/shims:/home/me/.pyenv/bin:/home/me/opt/miniconda3/bin:/home/me/opt/flutter/bin:/home/me/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
8 verbose lifecycle glamorous-website@1.0.0~precommit: CWD: /home/me/dev/contrib/glamorous-website
9 silly lifecycle glamorous-website@1.0.0~precommit: Args: [ '-c',
9 silly lifecycle   'lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"' ]
10 silly lifecycle glamorous-website@1.0.0~precommit: Returned: code: 1  signal: null
11 info lifecycle glamorous-website@1.0.0~precommit: Failed to exec precommit script
12 verbose stack Error: glamorous-website@1.0.0 precommit: `lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:194:7)
12 verbose stack     at ChildProcess.<anonymous> (/home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:194:7)
12 verbose stack     at maybeClose (internal/child_process.js:899:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid glamorous-website@1.0.0
14 verbose cwd /home/me/dev/contrib/glamorous-website
15 error Linux 4.10.0-22-generic
16 error argv "/home/me/.nvm/versions/node/v7.10.0/bin/node" "/home/me/.nvm/versions/node/v7.10.0/bin/npm" "run" "precommit"
17 error node v7.10.0
18 error npm  v4.2.0
19 error code ELIFECYCLE
20 error errno 1
21 error glamorous-website@1.0.0 precommit: `lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"`
21 error Exit status 1
22 error Failed at the glamorous-website@1.0.0 precommit script 'lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"'.
22 error Make sure you have the latest version of node.js and npm installed.
22 error If you do, this is most likely a problem with the glamorous-website package,
22 error not with npm itself.
22 error Tell the author that this fails on your system:
22 error     lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"
22 error You can get information on how to open an issue for this project with:
22 error     npm bugs glamorous-website
22 error Or if that isn't available, you can get their info via:
22 error     npm owner ls glamorous-website
22 error There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

**Comment by kentcdodds** [comment]
Don't worry about running `npm run commit`. Just commit like you would normally :)

**Comment by irth** [comment]
I opted in into the hooks and they ran automatically. After removing the .opt-in file they still ran somehow. I probably messed something up on my side. Nevermind. I renamed the hook in .git and commited: [here](https://github.com/irth/glamorous-website/commit/6032a0253bb7fcd9727f4f8002c0f06b5079b2a7)

**Comment by kentcdodds** [comment]
Well, there are _some_ git hooks that run whether you opt-in or not. But those should never fail 🤔 weird. And it looks like that's what's happening here actually. Did you get any more output?

**Comment by irth** [comment]
I ran it again. No .opt-in. Included everything there is.

## git commit
```
# me @ not-a-mac in ~/dev/contrib/glamorous-website on git:make-nav-localisable x [19:15:37] C:1
$ git status
On branch make-nav-localisable
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   .all-contributorsrc
	modified:   README.md


# me @ not-a-mac in ~/dev/contrib/glamorous-website on git:make-nav-localisable x [19:15:38] 
$ git commit 

> husky - npm run -s precommit
> husky - node v7.10.0

 ❯ Running tasks for .all-contributorsrc
   ✖ npm start contributors.generate && echo ignore arg
     →     at process._tickCallback (internal/process/next_tick.js:109:7)
     git add README.md && echo ignore arg
 ↓ Running tasks for *.js [skipped]
   → No staged files match *.js
🚫 npm start contributors.generate && echo ignore arg found some errors. Please fix them and try committing again.
nps is executing `contributors.generate`: all-contributors generate

TypeError: Cannot read property 'scriptName' of undefined
    at runPackageScript (/home/me/dev/contrib/glamorous-website/node_modules/nps/dist/index.js:95:35)
    at /home/me/dev/contrib/glamorous-website/node_modules/nps/dist/index.js:77:14
    at process._tickCallback (internal/process/next_tick.js:109:7)


> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
```

## npm run precommit
```
# me @ not-a-mac in ~/dev/contrib/glamorous-website on git:make-nav-localisable x [19:16:18] 
$ npm run precommit

> glamorous-website@1.0.0 precommit /home/me/dev/contrib/glamorous-website
> lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"

 ❯ Running tasks for .all-contributorsrc
   ✖ npm start contributors.generate && echo ignore arg
     → npm ERR!     /home/me/.npm/_logs/2017-06-15T17_16_21_672Z-debug.log
     git add README.md && echo ignore arg
 ↓ Running tasks for *.js [skipped]
   → No staged files match *.js
🚫 npm start contributors.generate && echo ignore arg found some errors. Please fix them and try committing again.

> glamorous-website@1.0.0 start /home/me/dev/contrib/glamorous-website
> nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"

nps is executing `contributors.generate`: all-contributors generate

TypeError: Cannot read property 'scriptName' of undefined
    at runPackageScript (/home/me/dev/contrib/glamorous-website/node_modules/nps/dist/index.js:95:35)
    at /home/me/dev/contrib/glamorous-website/node_modules/nps/dist/index.js:77:14
    at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Linux 4.10.0-22-generic
npm ERR! argv "/home/me/.nvm/versions/node/v7.10.0/bin/node" "/home/me/.nvm/versions/node/v7.10.0/bin/npm" "start" "contributors.generate" "&&" "echo" "ignore" "arg" "--" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! glamorous-website@1.0.0 start: `nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glamorous-website@1.0.0 start script 'nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the glamorous-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs glamorous-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls glamorous-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/.npm/_logs/2017-06-15T17_16_21_672Z-debug.log


npm ERR! Linux 4.10.0-22-generic
npm ERR! argv "/home/me/.nvm/versions/node/v7.10.0/bin/node" "/home/me/.nvm/versions/node/v7.10.0/bin/npm" "run" "precommit"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! glamorous-website@1.0.0 precommit: `lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glamorous-website@1.0.0 precommit script 'lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the glamorous-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs glamorous-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls glamorous-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/.npm/_logs/2017-06-15T17_16_21_698Z-debug.log
```

## /home/me/.npm/_logs/2017-06-15T17_16_21_672Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/me/.nvm/versions/node/v7.10.0/bin/node',
1 verbose cli   '/home/me/.nvm/versions/node/v7.10.0/bin/npm',
1 verbose cli   'start',
1 verbose cli   'contributors.generate',
1 verbose cli   '&&',
1 verbose cli   'echo',
1 verbose cli   'ignore',
1 verbose cli   'arg',
1 verbose cli   '--',
1 verbose cli   '/home/me/dev/contrib/glamorous-website/.all-contributorsrc' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle glamorous-website@1.0.0~prestart: glamorous-website@1.0.0
6 silly lifecycle glamorous-website@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle glamorous-website@1.0.0~start: glamorous-website@1.0.0
8 verbose lifecycle glamorous-website@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle glamorous-website@1.0.0~start: PATH: /home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/home/me/dev/contrib/glamorous-website/node_modules/.bin:/home/me/dev/contrib/glamorous-website/node_modules/.bin:/home/me/dev/contrib/node_modules/.bin:/home/me/dev/node_modules/.bin:/home/me/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/home/me/.nvm/versions/node/v7.10.0/bin:/home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/home/me/dev/contrib/glamorous-website/node_modules/.bin:/home/me/opt/miniconda3/bin:/home/me/.rbenv/shims:/home/me/.rbenv/bin:/home/me/.nvm/versions/node/v7.10.0/bin:/home/me/.pyenv/plugins/pyenv-virtualenv/shims:/home/me/.pyenv/shims:/home/me/.pyenv/bin:/home/me/opt/miniconda3/bin:/home/me/opt/flutter/bin:/home/me/bin:/home/me/.pyenv/plugins/pyenv-virtualenv/shims:/home/me/.pyenv/shims:/home/me/.pyenv/bin:/home/me/opt/miniconda3/bin:/home/me/opt/flutter/bin:/home/me/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle glamorous-website@1.0.0~start: CWD: /home/me/dev/contrib/glamorous-website
11 silly lifecycle glamorous-website@1.0.0~start: Args: [ '-c',
11 silly lifecycle   'nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"' ]
12 silly lifecycle glamorous-website@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle glamorous-website@1.0.0~start: Failed to exec start script
14 verbose stack Error: glamorous-website@1.0.0 start: `nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid glamorous-website@1.0.0
16 verbose cwd /home/me/dev/contrib/glamorous-website
17 error Linux 4.10.0-22-generic
18 error argv "/home/me/.nvm/versions/node/v7.10.0/bin/node" "/home/me/.nvm/versions/node/v7.10.0/bin/npm" "start" "contributors.generate" "&&" "echo" "ignore" "arg" "--" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error glamorous-website@1.0.0 start: `nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"`
23 error Exit status 1
24 error Failed at the glamorous-website@1.0.0 start script 'nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the glamorous-website package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     nps "contributors.generate" "&&" "echo" "ignore" "arg" "/home/me/dev/contrib/glamorous-website/.all-contributorsrc"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs glamorous-website
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls glamorous-website
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

## /home/me/.npm/_logs/2017-06-15T17_16_21_698Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/me/.nvm/versions/node/v7.10.0/bin/node',
1 verbose cli   '/home/me/.nvm/versions/node/v7.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'precommit' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'precommit' ]
5 info lifecycle glamorous-website@1.0.0~precommit: glamorous-website@1.0.0
6 verbose lifecycle glamorous-website@1.0.0~precommit: unsafe-perm in lifecycle true
7 verbose lifecycle glamorous-website@1.0.0~precommit: PATH: /home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/home/me/dev/contrib/glamorous-website/node_modules/.bin:/home/me/opt/miniconda3/bin:/home/me/.rbenv/shims:/home/me/.rbenv/bin:/home/me/.nvm/versions/node/v7.10.0/bin:/home/me/.pyenv/plugins/pyenv-virtualenv/shims:/home/me/.pyenv/shims:/home/me/.pyenv/bin:/home/me/opt/miniconda3/bin:/home/me/opt/flutter/bin:/home/me/bin:/home/me/.pyenv/plugins/pyenv-virtualenv/shims:/home/me/.pyenv/shims:/home/me/.pyenv/bin:/home/me/opt/miniconda3/bin:/home/me/opt/flutter/bin:/home/me/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
8 verbose lifecycle glamorous-website@1.0.0~precommit: CWD: /home/me/dev/contrib/glamorous-website
9 silly lifecycle glamorous-website@1.0.0~precommit: Args: [ '-c',
9 silly lifecycle   'lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"' ]
10 silly lifecycle glamorous-website@1.0.0~precommit: Returned: code: 1  signal: null
11 info lifecycle glamorous-website@1.0.0~precommit: Failed to exec precommit script
12 verbose stack Error: glamorous-website@1.0.0 precommit: `lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:194:7)
12 verbose stack     at ChildProcess.<anonymous> (/home/me/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:194:7)
12 verbose stack     at maybeClose (internal/child_process.js:899:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid glamorous-website@1.0.0
14 verbose cwd /home/me/dev/contrib/glamorous-website
15 error Linux 4.10.0-22-generic
16 error argv "/home/me/.nvm/versions/node/v7.10.0/bin/node" "/home/me/.nvm/versions/node/v7.10.0/bin/npm" "run" "precommit"
17 error node v7.10.0
18 error npm  v4.2.0
19 error code ELIFECYCLE
20 error errno 1
21 error glamorous-website@1.0.0 precommit: `lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"`
21 error Exit status 1
22 error Failed at the glamorous-website@1.0.0 precommit script 'lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"'.
22 error Make sure you have the latest version of node.js and npm installed.
22 error If you do, this is most likely a problem with the glamorous-website package,
22 error not with npm itself.
22 error Tell the author that this fails on your system:
22 error     lint-staged && opt --in pre-commit --exec "npm start validate && npm start build.clean"
22 error You can get information on how to open an issue for this project with:
22 error     npm bugs glamorous-website
22 error Or if that isn't available, you can get their info via:
22 error     npm owner ls glamorous-website
22 error There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

**Comment by kentcdodds** [comment]
Ah, yeah, this:

```
TypeError: Cannot read property 'scriptName' of undefined
    at runPackageScript (/home/me/dev/contrib/glamorous-website/node_modules/nps/dist/index.js:95:35)
    at /home/me/dev/contrib/glamorous-website/node_modules/nps/dist/index.js:77:14
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Is the error. I'm not sure why that's happening, but try [updating your branch](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch) and running `yarn` (or `npm install`) again to see if that fixes things. Sorry for all the trouble! Thanks for wading through this so we can improve it!

**Comment by irth** [comment]
the exact same thing happens :/

also, i can run `nps contributors.generate` on its own and it works

```
# me @ not-a-mac in ~/dev/contrib/glamorous-website on git:make-nav-localisable x [19:38:21] 
$ node_modules/.bin/nps contributors.generate
nps is executing `contributors.generate`: all-contributors generate

# me @ not-a-mac in ~/dev/contrib/glamorous-website on git:make-nav-localisable x [19:38:26] 
$ echo $?                                    
0
```

**Comment by kentcdodds** [comment]
Possibly! Sorry about that. Go ahead and commit your changes with `git commit -am "your message" --no-verify`

**Comment by irth** [comment]
I just did. Sorry for wasting your time. Should I open another pull request?

**Comment by kentcdodds** [comment]
No worries! Yeah, open another PR :+1: Thanks!

**Comment by irth** [comment]
[Done!](https://github.com/kentcdodds/glamorous-website/pull/146) Thanks.

**Pull request merged**
