### PR TITLE
Feature/search

### PR DESCRIPTION
**Pull request by RIanDeLaCruz**
**What**: Added Search functionality via Algolia

**Why**: Site Usability

**How**: Using Algolia DocSearch

### CODE REVIEW

**Comment by RIanDeLaCruz** [comment]
I'm not sure, at this point, how to style.

Tried using Glamorous itself but it seems as if I am missing something for the style to appear

**Comment by RIanDeLaCruz** [comment]
screen shot 2017-07-10 at 9 09 17 pm
I'll upload to now for a sample

**Comment by kentcdodds** [comment]
Thanks @RIanDeLaCruz! I just force-pushed to your branch to resolve some merge conflicts (your branch was pretty out of date :sweat_smile:). Please make sure you pull before doing any more work.

Could we get help here from someone? How should we style this? cc @jonmajorc, do you have any ideas?

By the way, this is AWESOME!!!!

search

**Comment by RIanDeLaCruz** [comment]
Thanks! 😄

**Comment by motleydev** [comment]
Ok, I have a style to be reviewed. I'm running into some knowledge limit with github though. :) How do I push my version of this branch back to this feed? I added this branch as a remote but I am assuming I don't have write access?

**Comment by motleydev** [comment]
search-interaction

**Comment by kentcdodds** [comment]
Closing in favor of #235

**Pull request closed without merging**
