### PR TITLE
Twitter Card for the website

### PR DESCRIPTION
**Pull request by iamrudra**
**What**: This adds required meta tags to the page required for the twitter card

**Why**: To have an awesome twitter card that the website deserves ;)

**How**: Meta tags were added with required attributes

The banner.png has been added to the static/images directory for future use. I could not get twitter to take a relative path. So right now it is pointing to the github user content URL. Per my understanding, we will need to modify this once we deploy the site and have a URL for the image. 

Here's the [now deployment](https://glamorous-website-bpkmieniim.now.sh/) to test on the [twitter card validator](https://cards-dev.twitter.com/validator).

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome! On the validator I just saw this:

screen shot 2017-05-31 at 2 52 57 pm


I seem to remember something about this, but can't remember exactly. Do we need to do something to validate https://glamorous.rocks ?

**Comment by kentcdodds** [comment]
> So right now it is pointing to the github user content URL.

That's fine. Let's try to remember to update that after we've gone live :)

**Comment by kentcdodds** [comment]
This is great. Thanks a ton!

**Comment by iamrudra** [comment]
>I seem to remember something about this, but can't remember exactly. Do we need to do something to validate https://glamorous.rocks ?

I saw that too the first time when I validated this card. Not much idea on what that is and how to get it whitelisted.

**Comment by kentcdodds** [comment]
Sweet. I updated https://glamorous.rocks/ to use the same meta tags you have here and tried the validator and it totally works :)

Super awesome!

screen shot 2017-05-31 at 4 04 42 pm

**Comment by kentcdodds** [comment]
Sweet, [the first @glamorousCSS tweet](https://twitter.com/glamorousCSS/status/869963769660686336) has been updated with the new preview. This is awesome!

screen shot 2017-05-31 at 4 11 27 pm

**Pull request merged**
